#!/bin/bash
TRACK_HOME=$(cd $(dirname $0)/.. ; pwd -P )
TRACK_HOME=$(cd "$(dirname "$0")" ; pwd -P )
TRACK_HOME=$TRACK_HOME
echo ${TRACK_HOME}
cd "${TRACK_HOME}"
cd lib

node filegen.js m_repltemp -taskname-html_test -fullname-myfilename  -id-XXXXX -width-120 -height-600 -mainindex-index.html -landing-http%3A%2F%2Ftwindai.com 
